# Generated by Django 4.1.2 on 2022-10-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(default='null', upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
